# Generated by Django 5.0.6 on 2024-06-25 21:03

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('processo', models.BooleanField(verbose_name='Processo obbligatorio')),
                ('owner', models.BooleanField(verbose_name='Owner obbligatorio')),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Disposizioni',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('data_disposizione', models.DateField(default=django.utils.timezone.now, verbose_name='Data disposizione')),
                ('numero', models.PositiveSmallIntegerField(unique_for_year='data_disposizione', verbose_name='Numero disposizione')),
                ('stato', models.CharField(choices=[('DR', 'Da recepire'), ('RE', 'Recepita'), ('AP', 'Approvata'), ('IN', 'Informativa'), ('NA', 'Non applicabile')], default='DR', max_length=2)),
            ],
            options={
                'verbose_name': 'Disposizione',
                'verbose_name_plural': 'Disposizioni',
            },
        ),
        migrations.CreateModel(
            name='Domande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domanda', models.TextField()),
                ('risposta', models.TextField(blank=True, null=True)),
                ('data_creazione', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Domanda',
                'verbose_name_plural': 'Domande',
            },
        ),
        migrations.CreateModel(
            name='TipiUnitaOrganizzative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=30, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo Unità Organizzativa',
                'verbose_name_plural': 'Tipi Unità Organizzative',
            },
        ),
        migrations.CreateModel(
            name='LegalEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, unique=True)),
                ('quota_controllata', models.DecimalField(decimal_places=2, default=0, max_digits=5, verbose_name='controllo')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='normativa.legalentity', verbose_name='Controllante')),
            ],
            options={
                'verbose_name': 'Legal Entity',
                'verbose_name_plural': 'Legal Entity',
            },
        ),
        migrations.CreateModel(
            name='UnitaOrganizzative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100, unique=True)),
                ('LegalEntity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='normativa.legalentity')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='normativa.unitaorganizzative', verbose_name='Unita superiore')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='normativa.tipiunitaorganizzative')),
            ],
            options={
                'verbose_name': 'Unità Organizzativa',
                'verbose_name_plural': 'Unità Organizzative',
            },
        ),
        migrations.CreateModel(
            name='Processi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='normativa.processi', verbose_name='Processo padre')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='normativa.unitaorganizzative')),
            ],
            options={
                'verbose_name': 'Processo',
                'verbose_name_plural': 'Processi',
            },
        ),
        migrations.CreateModel(
            name='Documenti',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrizione', models.CharField(max_length=100)),
                ('data_pubblicazione', models.DateField(blank=True, null=True)),
                ('file_name', models.CharField(blank=True, max_length=255, null=True)),
                ('data_approvazione', models.DateField(blank=True, null=True)),
                ('testo', models.TextField(blank=True, null=True)),
                ('modo', models.CharField(blank=True, choices=[('RE', 'Recepita'), ('AP', 'Approvata')], default='RE', max_length=2, null=True)),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='normativa.categorie')),
                ('disposizione', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='normativa.disposizioni')),
                ('legal_entity_controllante', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_controllante', to='normativa.legalentity')),
                ('legal_entity_controllata', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_controllata', to='normativa.legalentity')),
                ('processo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='normativa.processi')),
                ('owner_controllante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_controllante', to='normativa.unitaorganizzative')),
                ('owner_controllata', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_controllata', to='normativa.unitaorganizzative')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documenti',
            },
        ),
        migrations.AddField(
            model_name='disposizioni',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='normativa.unitaorganizzative'),
        ),
    ]
