# Generated by Django 5.0.6 on 2024-06-25 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenti',
            name='legal_entity_controllante',
        ),
        migrations.RemoveField(
            model_name='documenti',
            name='legal_entity_controllata',
        ),
    ]
