# Generated by Django 5.0.6 on 2024-06-25 21:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0002_remove_documenti_legal_entity_controllante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenti',
            name='legal_entity_controllante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_controllante', to='normativa.legalentity'),
        ),
        migrations.AddField(
            model_name='documenti',
            name='legal_entity_controllata',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_controllata', to='normativa.legalentity'),
        ),
    ]
