# Generated by Django 5.0.6 on 2024-06-30 13:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0003_documenti_legal_entity_controllante_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='processi',
            name='LegalEntity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='normativa.legalentity'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documenti',
            name='legal_entity_controllante',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_controllante', to='normativa.legalentity', verbose_name='controllante'),
        ),
        migrations.AlterField(
            model_name='documenti',
            name='legal_entity_controllata',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, related_name='legal_entity_controllata', to='normativa.legalentity', verbose_name='controllata'),
        ),
    ]
