# Generated by Django 5.0.6 on 2024-07-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0004_processi_legalentity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenti',
            name='trained',
            field=models.BooleanField(default=False),
        ),
    ]
