# Generated by Django 5.0.6 on 2024-07-28 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0005_documenti_trained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenti',
            name='testo',
        ),
        migrations.AlterField(
            model_name='documenti',
            name='trained',
            field=models.BooleanField(default=False, verbose_name='Addestrato'),
        ),
    ]
