# Generated by Django 5.0.6 on 2024-08-06 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0006_remove_documenti_testo_alter_documenti_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='domande',
            name='auto_generated',
            field=models.BooleanField(default=True, verbose_name='Generato'),
        ),
        migrations.AddField(
            model_name='domande',
            name='documento',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.PROTECT, to='normativa.documenti', verbose_name='documento'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='domande',
            name='rating',
            field=models.IntegerField(default=1, verbose_name='rating'),
            preserve_default=False,
        ),
    ]
