# Generated by Django 5.0.6 on 2024-08-07 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0007_domande_auto_generated_domande_documento_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='domande',
            name='context_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
