# Generated by Django 5.0.6 on 2024-08-18 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0008_domande_context_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domande',
            name='rating',
        ),
        migrations.AddField(
            model_name='domande',
            name='rating_domanda',
            field=models.FloatField(default=None, verbose_name='Rating domanda'),
        ),
        migrations.AddField(
            model_name='domande',
            name='rating_risposta',
            field=models.FloatField(default=None, verbose_name='Rating risposta'),
        ),
    ]
