# Generated by Django 5.0.6 on 2024-08-18 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0010_alter_domande_rating_domanda_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domande',
            name='rating_domanda',
            field=models.FloatField(default=0, verbose_name='Rating domanda'),
        ),
        migrations.AlterField(
            model_name='domande',
            name='rating_risposta',
            field=models.FloatField(default=0, verbose_name='Rating risposta'),
        ),
    ]
