# Generated by Django 5.0.6 on 2024-08-24 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0011_alter_domande_rating_domanda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenti',
            name='qg_trained',
            field=models.BooleanField(default=False, verbose_name='QG trained'),
        ),
    ]
