# Generated by Django 5.0.6 on 2024-08-25 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0012_documenti_qg_trained'),
    ]

    operations = [
        migrations.AddField(
            model_name='documenti',
            name='ag_trained',
            field=models.BooleanField(default=False, verbose_name='AG trained'),
        ),
    ]
