# Generated by Django 5.0.6 on 2024-08-25 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('normativa', '0013_documenti_ag_trained'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documenti',
            name='trained',
        ),
    ]
